baseURL = 'https://jbcr.pt/'
languageCode = 'en-us'
title = "João Rodrigues' Slick Site"

theme = 'lugo'


[markup]
  [markup.highlight]
    noClasses = true      # Use CSS classes for styling
    style = "gruvbox"       # Choose a color scheme (e.g., "dracula", "monokai", etc.)
    lineNos = false          # Show line numbers if desired
    lineNumbersInTable = true # Places line numbers in a table
